### ISSUE TITLE
Misspelling of `KinesisLogSource` as `KineisLogSource`

### ISSUE THREAD

**Issue by flatherskevin** [pulumi/pulumi-sumologic#452]
### Describe what happened

The class name for Kinesis Logs is misspelt as `KineisLogSource`, when it should be `KinesisLogSource`

### Sample program

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @flatherskevin. Thanks for opening an issue. We'll get this fixed in the next release.
